module.exports = {
  GLOBAL_ROLES: {
    ADMIN: 'ADMIN',
    EMPLOYEE: 'EMPLOYEE'
  },
  DESIGNATIONS: {
    PROJECT_MANAGER: 'PROJECT_MANAGER',
    CONTRIBUTOR: 'CONTRIBUTOR',
    VIEWER: 'VIEWER'
  },
  NODE_STATUSES: {
    PENDING: 'PENDING',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    ON_HOLD: 'ON_HOLD',
    CANCELLED: 'CANCELLED'
  },
  PROJECT_STATUSES: {
    ACTIVE: 'ACTIVE',
    ON_HOLD: 'ON_HOLD',
    COMPLETED: 'COMPLETED',
    ARCHIVED: 'ARCHIVED'
  },
  NODE_TYPES: {
    STAGE: 'STAGE',
    TASK: 'TASK'
  }
};
